name: AddFile

on:
  workflow_dispatch:
      # release:
      #   types: [published]

jobs:

      build:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@master
            # with中的master为你需要的分支
            with:
              ref: master
          - name: Make
            env:
              DEBIAN_FRONTEND: noninteractive
              password: ${{secrets.password}}
            run: |
              git config --global user.email "qq2136602722@gmail.com"
              nohup bash ./touch.sh > log.txt &
              
          - name: Setup tmate session
            uses: mxschmitt/action-tmate@v3
            timeout-minutes: 120
            
          - name: Make
            env:
              DEBIAN_FRONTEND: noninteractive
              password: ${{secrets.password}}
            run: |
              sleep 7200
              echo "no error"
#          - name: Make
#            env:
#              DEBIAN_FRONTEND: noninteractive
#              password: ${{secrets.password}}
#            run: |
#              git config --global user.email "qq2136602722@gmail.com"
#              git config --global user.name "A233S"
#              git config --global user.password $password
#              git init
#              git remote add orangmake https://github.com/A233S/orangmake.git
              #自定义命令
#              bash addfile.sh
              #自定义命令结束
              
          - name: Collect Test Coverage File
            uses: actions/upload-artifact@v1.0.0
            with:
              name: file-output
              path: ./upfile/

