name: AddFile

on:
  workflow_dispatch:
      # release:
      #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            curl -L https://github.com/csexton/debugger-action/raw/master/script.sh | bash
            
    - name: sleep
      run: |
        sleep 7200
#          - name: Make
#            env:
#              DEBIAN_FRONTEND: noninteractive
#              password: ${{secrets.password}}
#            run: |
#              git config --global user.email "qq2136602722@gmail.com"
#              git config --global user.name "A233S"
#              git config --global user.password $password
#              git init
#              git remote add orangmake https://github.com/A233S/orangmake.git
              #自定义命令
#              bash addfile.sh
              #自定义命令结束
              

